.TH man 1 "27 August 2022" "1.0.0" "xivlauncher-core man page"
.SH NAME
xivlauncher-core \- Unofficial launcher for Final Fantasy XIV
.SH SYNOPSIS
xivlauncher-core
.SH DESCRIPTION
.PP
XIVLauncher Core is a native Linux application for launching the massive
multiplayer game Final Fantasy XIV. It is entirely self-contained, integrates
with the native Linux version of Steam, and does not require a Wine
installation to function.
.PP
XIVLauncher Core is a graphical application for the X Window System.
.SH OPTIONS
xivlauncher-core has no options.
.SH BUGS
Please report bugs to https://github.com/goatcorp/FFXIVQuickLauncher.
.SH AUTHOR
This manual page was written by Maia Everett <maia@everett.one>.
